// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8b-bKvAGTtT26TmBnQk6zL_D1Lrc8a0o',
    appId: '1:388261259361:android:22bf7e702f7e657f0c6220',
    messagingSenderId: '388261259361',
    projectId: 'halalspots-5d879',
    databaseURL: 'https://halalspots-5d879-default-rtdb.firebaseio.com',
    storageBucket: 'halalspots-5d879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCojqhjKIBXbqlP0AOZQ-vjUxZxvVry5I',
    appId: '1:388261259361:ios:fb9a4c1894ffdfa60c6220',
    messagingSenderId: '388261259361',
    projectId: 'halalspots-5d879',
    databaseURL: 'https://halalspots-5d879-default-rtdb.firebaseio.com',
    storageBucket: 'halalspots-5d879.appspot.com',
    iosBundleId: 'com.example.halalSpots',
  );

}