name: halal_spots
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0  # Compatible with Flutter 3.x
  firebase_auth: ^5.3.0  # Compatible with Flutter 3.x
  cloud_firestore: ^5.4.0  # Compatible with Flutter 3.x
  firebase_storage: ^12.3.0  # Compatible with Flutter 3.x
  google_fonts: ^6.2.1  # Downgraded to a compatible version
  intl: ^0.17.0  # Compatible with Flutter 3.x
  image_picker: ^1.0.4  # Compatible with Flutter 3.x
  carousel_slider: ^5.0.0  # Compatible with Flutter 3.x
  flutter_clean_calendar: ^1.1.0  # Compatible with Flutter 3.x
  readmore: ^3.0.0  # Compatible with Flutter 3.x
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  url_launcher: ^6.0.12
  timeago: ^3.1.0
  latlong2: ^0.9.0
  location: ^7.0.1
  shared_preferences: ^2.0.15
  dropdown_search: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_plugin_android_lifecycle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - images/whole_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/whole_logo.png"